### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by valent** [TobCar/cryptocurrency-trader#1]
How do i run this?

THanks

**Comment by TobCar** [comment]
Look for a file ending with _operator. For example, in the Cryptopia folder, there is a file named cryptopia_operator. If you run that file the bot will run whatever strategy is set as the default for that exchange.

**Comment by valent** [comment]
Thanks. Still getting errors;

Traceback (most recent call last):
  File "cryptotrader\cryptopia\cryptopia_operator.py", line 5, in <module>
    from cryptotrader.tradesignals.strategies.spread_size_strategy import SpreadSizeStrategy
ModuleNotFoundError: No module named 'cryptotrader'

**Comment by TobCar** [comment]
I have the project in Eclipse such that cryptotrader is the root module. The error you're getting implies that cryptotrader is not the module. I recommend importing the project into an IDE and changing the import statements if they continue to fail.

Side note: It is not profitable to have everyone using the same strategies. The strategies included with the bot are intended to be expanded upon. Feel free to fork the project and customize the strategies until they are profitable for you. At the very least you'll want to change the coin the bot is trading in the operator file.

**Comment by valent** [comment]
Thanks a lot for this. Will make the necessary changes and adjust the strategy to fit my style of trade.

**Comment by TobCar** [comment]
No problem! I'm happy to help. :)
